#!/bin/sh
#
# CIP Core, generic profile
#
# Copyright (c) Siemens AG, 2019
# Copyright (c) Cybertrust Japan Co., Ltd., 2021
#
# Authors:
#  Jan Kiszka <jan.kiszka@siemens.com>
#  Alice Ferrazzi <alice.ferrazzi@miraclelinux.com>
#
# SPDX-License-Identifier: MIT
#

echo "CIP Core Demo & Test Image" > /etc/issue

# permit root login without password
echo "PermitRootLogin yes" >> /etc/ssh/sshd_config
echo "PermitEmptyPasswords yes" >> /etc/ssh/sshd_config
passwd root -d

# serial getty service for autologin
mkdir -p /etc/systemd/system/serial-getty@.service.d/
echo "[Service]" > /etc/systemd/system/serial-getty@.service.d/override.conf
echo "ExecStart=" >> /etc/systemd/system/serial-getty@.service.d/override.conf
echo "ExecStart=-/sbin/agetty --autologin root --keep-baud 115200,38400,9600 %I $TERM" >> /etc/systemd/system/serial-getty@.service.d/override.conf

# set the profile for KernelCI
echo "PS1='\$(pwd) # '" > /root/.profile
echo "cd /" >> /root/.profile

HOSTNAME=demo
echo "$HOSTNAME" > /etc/hostname
echo "127.0.0.1 $HOSTNAME" >> /etc/hosts
