#!/bin/sh
#
# CIP Core, generic profile
#
# Copyright (c) Siemens AG, 2019
#
# Authors:
#  Jan Kiszka <jan.kiszka@siemens.com>
#
# SPDX-License-Identifier: MIT
#

echo "CIP Core Demo & Test Image (login: root/root)" > /etc/issue

echo "PermitRootLogin yes" >> /etc/ssh/sshd_config

HOSTNAME=demo
echo "$HOSTNAME" > /etc/hostname
echo "127.0.0.1 $HOSTNAME" >> /etc/hosts

# needed for read-only rootfs with writable /home
mv /root /home/
ln -s /home/root /root
