#!/bin/sh
#
# CIP Core, generic profile
#
# Copyright (c) Siemens AG, 2019
#
# Authors:
#  Jan Kiszka <jan.kiszka@siemens.com>
#
# SPDX-License-Identifier: MIT
#

echo "CIP Core Demo & Test Image (login: root/root)" > /etc/issue

echo "PermitRootLogin yes" >> /etc/ssh/sshd_config

echo "demo" > /etc/hostname
